// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetWordsReader is a Reader for the GetWords structure.
type GetWordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /words] GetWords", response, response.Code())
	}
}

// NewGetWordsOK creates a GetWordsOK with default headers values
func NewGetWordsOK() *GetWordsOK {
	return &GetWordsOK{}
}

/*
GetWordsOK describes a response with status code 200, with default header values.

the user's words from the given user dictionaries
*/
type GetWordsOK struct {
	Payload *GetWordsOKBody
}

// IsSuccess returns true when this get words o k response has a 2xx status code
func (o *GetWordsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get words o k response has a 3xx status code
func (o *GetWordsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get words o k response has a 4xx status code
func (o *GetWordsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get words o k response has a 5xx status code
func (o *GetWordsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get words o k response a status code equal to that given
func (o *GetWordsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get words o k response
func (o *GetWordsOK) Code() int {
	return 200
}

func (o *GetWordsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /words][%d] getWordsOK %s", 200, payload)
}

func (o *GetWordsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /words][%d] getWordsOK %s", 200, payload)
}

func (o *GetWordsOK) GetPayload() *GetWordsOKBody {
	return o.Payload
}

func (o *GetWordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetWordsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetWordsOKBody get words o k body
swagger:model GetWordsOKBody
*/
type GetWordsOKBody struct {

	// array of words
	Words []string `json:"words"`
}

// Validate validates this get words o k body
func (o *GetWordsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get words o k body based on context it is used
func (o *GetWordsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetWordsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWordsOKBody) UnmarshalBinary(b []byte) error {
	var res GetWordsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
