// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostWordsAddParams creates a new PostWordsAddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostWordsAddParams() *PostWordsAddParams {
	return &PostWordsAddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostWordsAddParamsWithTimeout creates a new PostWordsAddParams object
// with the ability to set a timeout on a request.
func NewPostWordsAddParamsWithTimeout(timeout time.Duration) *PostWordsAddParams {
	return &PostWordsAddParams{
		timeout: timeout,
	}
}

// NewPostWordsAddParamsWithContext creates a new PostWordsAddParams object
// with the ability to set a context for a request.
func NewPostWordsAddParamsWithContext(ctx context.Context) *PostWordsAddParams {
	return &PostWordsAddParams{
		Context: ctx,
	}
}

// NewPostWordsAddParamsWithHTTPClient creates a new PostWordsAddParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostWordsAddParamsWithHTTPClient(client *http.Client) *PostWordsAddParams {
	return &PostWordsAddParams{
		HTTPClient: client,
	}
}

/*
PostWordsAddParams contains all the parameters to send to the API endpoint

	for the post words add operation.

	Typically these are written to a http.Request.
*/
type PostWordsAddParams struct {

	/* APIKey.

	   <a target='_blank' href='https://languagetool.org/editor/settings/access-tokens'>Your API key</a>

	   Format: password
	*/
	APIKey strfmt.Password

	/* Dict.

	   Name of the dictionary to add the word to; non-existent dictionaries are created after calling this; if unset, adds to special default dictionary
	*/
	Dict *string

	/* Username.

	   Your username as used to log in at languagetool.org.
	*/
	Username string

	/* Word.

	   The word to be added. Must not be a phrase, i.e. cannot contain white space. The word is added to a global dictionary that applies to all languages.
	*/
	Word string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post words add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostWordsAddParams) WithDefaults() *PostWordsAddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post words add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostWordsAddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post words add params
func (o *PostWordsAddParams) WithTimeout(timeout time.Duration) *PostWordsAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post words add params
func (o *PostWordsAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post words add params
func (o *PostWordsAddParams) WithContext(ctx context.Context) *PostWordsAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post words add params
func (o *PostWordsAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post words add params
func (o *PostWordsAddParams) WithHTTPClient(client *http.Client) *PostWordsAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post words add params
func (o *PostWordsAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIKey adds the aPIKey to the post words add params
func (o *PostWordsAddParams) WithAPIKey(aPIKey strfmt.Password) *PostWordsAddParams {
	o.SetAPIKey(aPIKey)
	return o
}

// SetAPIKey adds the apiKey to the post words add params
func (o *PostWordsAddParams) SetAPIKey(aPIKey strfmt.Password) {
	o.APIKey = aPIKey
}

// WithDict adds the dict to the post words add params
func (o *PostWordsAddParams) WithDict(dict *string) *PostWordsAddParams {
	o.SetDict(dict)
	return o
}

// SetDict adds the dict to the post words add params
func (o *PostWordsAddParams) SetDict(dict *string) {
	o.Dict = dict
}

// WithUsername adds the username to the post words add params
func (o *PostWordsAddParams) WithUsername(username string) *PostWordsAddParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the post words add params
func (o *PostWordsAddParams) SetUsername(username string) {
	o.Username = username
}

// WithWord adds the word to the post words add params
func (o *PostWordsAddParams) WithWord(word string) *PostWordsAddParams {
	o.SetWord(word)
	return o
}

// SetWord adds the word to the post words add params
func (o *PostWordsAddParams) SetWord(word string) {
	o.Word = word
}

// WriteToRequest writes these params to a swagger request
func (o *PostWordsAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param apiKey
	frAPIKey := o.APIKey
	fAPIKey := frAPIKey.String()
	if fAPIKey != "" {
		if err := r.SetFormParam("apiKey", fAPIKey); err != nil {
			return err
		}
	}

	if o.Dict != nil {

		// form param dict
		var frDict string
		if o.Dict != nil {
			frDict = *o.Dict
		}
		fDict := frDict
		if fDict != "" {
			if err := r.SetFormParam("dict", fDict); err != nil {
				return err
			}
		}
	}

	// form param username
	frUsername := o.Username
	fUsername := frUsername
	if fUsername != "" {
		if err := r.SetFormParam("username", fUsername); err != nil {
			return err
		}
	}

	// form param word
	frWord := o.Word
	fWord := frWord
	if fWord != "" {
		if err := r.SetFormParam("word", fWord); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
